### ISSUE TITLE
[suggestion] chat color

### ISSUE THREAD

**Issue by zeteticl** [NanasuNANA/UdonariumWithFly#12]
i hope private chat text with color too
Now the text color  will show grey. 
hard to identify user. 

![9D0D4ABD-270C-4E52-B202-2A9108246871](https://user-images.githubusercontent.com/23254376/120904615-ab2e0c00-c67f-11eb-9222-68dfbfbeaed6.jpeg)

**Comment by NanasuNANA** [comment]
The color will be reflected in the name in the next update.
