### ISSUE TITLE
[question] how to use 💭?

### ISSUE THREAD

**Issue by zeteticl** [NanasuNANA/UdonariumWithFly#15]
When i enter ?/??/??? it can show the text with 💭
but ???? or test  or some word it wont enable the 💭?
How can i enter 💭 function?

![image](https://user-images.githubusercontent.com/23254376/129665897-bdbf5372-0664-4a96-b6d7-e35a0be41bb7.png)

![image](https://user-images.githubusercontent.com/23254376/129665969-1ecce559-7782-4bea-bf6f-50b9618272d1.png)

no 💭
![image](https://user-images.githubusercontent.com/23254376/129665994-7ec45f89-d2ed-4564-8b24-a27a126bb2cf.png)

**Comment by NanasuNANA** [comment]
An experimental simple emote feature, text with up to 3 symbols will be displayed as such.

**Comment by NanasuNANA** [comment]
A speech balloon displays the text enclosed in "「", "」".

**Comment by zeteticl** [comment]
got it! Thankyou for your reply!
