### ISSUE TITLE
[bug] 地形hight 0 

### ISSUE THREAD

**Issue by zeteticl** [NanasuNANA/UdonariumWithFly#17]
in https://udonarium.app/  that is run correctly
but in UdonariumWithFly, if the 地形 set to hight 0 
it couldnt to drag and move

https://user-images.githubusercontent.com/23254376/137316110-595ed6a1-d7f3-4251-a995-00e4b9c99781.mp4

**Comment by NanasuNANA** [comment]
Fixed in version 1.4.9
