### ISSUE TITLE
チャットパレットの変数展開での不具合

### ISSUE THREAD

**Issue by hoehoe-git** [NanasuNANA/UdonariumWithFly#18]
複数の変数入りのチャットパレットが、正しく展開されずコマンドエラーとなる場合があり、ダイスが振れません。
( ユドナリウムやユドナリウム 2d では正常にダイスが振れているチャットパレットです )
withFly ですと、チャットパレット行を選択した時点で変数が自動で代入されておりますが、1 つ目の変数は正常展開されるものの、2 つ目の変数展開で数字の前に半角スペースが入ってしまい ( 下記画像赤線部分 )、構文エラーとして BCDice が反応しないものと思われます。
![withfly_report_#1](https://user-images.githubusercontent.com/64144994/143267854-c9cad4d4-b2ff-4f7a-a35f-6c6763331764.png)

また、再現テストのために、新規キャラクターで同じチャットパレット文をセットしたところ、2 つ目の変数展開は正常にされたものの、1 つ目の変数参照が正しくされない ( 下記画像赤線部分 )、ということがあったことを加えて御報告致します。
![withfly_report_#2](https://user-images.githubusercontent.com/64144994/143267910-9ee358c7-d7c5-4936-903f-e8d97108f55e.png)

御確認の程、よろしくお願い致します。

**Comment by hoehoe-git** [comment]
申し訳ありません、上記ですが、前者の方は自己解決致しましたので取り下げさせて下さい。
2 つ目の変数名が、キャラクターシート詳細の方にも同名の情報があり、そちらを優先して展開しているためであることが分かりました。( 変数名を別の表記にしたところ、正しく展開出来るようになりました )
また後者の方ですが、これはパラメータ分類を能力値にすると、「 "項目名"修正 」 という変数が定義される、という認識で良いでしょうか？

**Comment by NanasuNANA** [comment]
これも文書化してなかったなあ。
リソース、能力値の場合

最大"項目名",
Max"項目名", Max_"項目名", Max:"項目名", Max "項目名"
基本"項目名",
初期"項目名",
原"項目名",
"項目名"基本値,
"項目名"初期値,
"項目名"原点

で元地/最大値を参照し、能力値の場合

"項目名"修正値,
"項目名" Mod, "項目名" Mod., "項目名" Modifire,
"項目名"ボーナス

で修正値を参照します。

**Comment by hoehoe-git** [comment]
御回答ありがとうございました！
本件クローズとさせていただきますね。
良いツールをありがとうございます。
