### ISSUE TITLE
不具合疑義：キャラクターのリソース項目をチェック項目に変更してインベントリリストに表示するとキャラクターポップアップが正常に表示されない

### ISSUE THREAD

**Issue by B-biker** [NanasuNANA/UdonariumWithFly#24]
失礼いたします。
こちらのUdonarium with Flyでオンラインセッションを行っておりましたところ
表記の事象を確認致しました。
以下に詳細を記載致しますので、ご確認頂けますと幸いです。

# 不具合疑義内容
キャラクターシート内のリソース項目をチェック項目に変更したうえで
インベントリリストにて当該項目を表示項目に加えた場合
そのキャラクターコマにマウスカーソルを重ねた際に正常な場所に表示されない

# 再現手順
1. Udonarium with Flyにアクセスする
2. 初期で配置されているキャラクターのうち、キャラクターBを右クリックする
3. 表示されたコンテキストメニュー上で「詳細を表示」をクリックする
4. 「編集切り替え」ボタンをクリックする
5. キャラクターシート内の大項目「情報」の横の＋ボタンを押下する
6. 作成された行の「通常」をクリックし、選択肢から「リソース」を選択してクリックする
7. 作成された行の「タグ」をクリックし、タグの文字列を「チェック項目」に変更する
8. 作成された行のリソース値の現在値および最大値をそれぞれ1に変更する
9. 作成された行の「リソース」をクリックし、選択肢から「チェック」を選択してクリックする
10. キャラクターシート画面右上の×ボタンをクリックしてキャラクターシート画面を閉じる
11. メニューから「インベントリ」をクリックする
12. インベントリの「設定」ボタンを押下する
13. 表示項目のテキストの末尾に半角スペースに続けて「チェック項目」と追記する
14. キャラクターBにマウスカーソルを重ねる

# 結果
キャラクターにマウスカーソルを重ねた際のポップアップが画面左端に表示される

# 期待する結果
キャラクターにマウスカーソルを重ねた際のポップアップが
キャラクターのすぐ近くに表示される

# 実行環境
サーバーURL：
https://nanasunana.github.io/
2022年9月6日23時50分の時点で事象を確認

クライアント環境：
OS: Windows 11 Home 21H2 OSビルド 22000.856
Google Chrome バージョン: 105.0.5195.102（Official Build） （64 ビット）

**Comment by NanasuNANA** [comment]
詳細な再現手順込みでの不具合報告ありがとうございます。
バージョン 1.7.5fにて修正しました。

**Comment by B-biker** [comment]
ご対応ありがとうございます。
迅速にご対応いただいたにも関わらず、返答が遅くなり誠に申し訳ございません。
