### ISSUE TITLE
テキストチャットログが累積した状態のみ視点角度変更操作が極端に重くなります。

### ISSUE THREAD

**Issue by Mazzn1987** [NanasuNANA/UdonariumWithFly#4]
お世話になっております。
チャットログが溜まった状態（5タブ、一番多いタブに500ログ程度）でチャットウィンドウを開いた状態だと視点角度変更（右クリックドラッグ）の捜査が極端に重くなりカクつく症状が出ます。
チャットウィンドウを閉じると通常通り操作するため、画面内にチャットウィンドウを開いたときのみなにか処理が重くなっていような挙動となります。
チャットログ量に依存するらしくログが溜まっていない状態ではチャットウィンドウが開いていても発生しません。
再現するセーブデータをdropboxリンクにて共有します。
ご確認いただきご対応いただけましたら幸いです。
https://www.dropbox.com/s/kqz2mr9b0clmjem/D%26D5e%E3%82%86%E3%82%8B%E3%81%B5%E3%82%8F%E9%AD%94%E6%B3%95%E5%AD%A6%E5%9C%92%E6%9C%80%E7%B5%82%E8%A9%B1_2021-03-09_2341.zip?dl=1

**Comment by NanasuNANA** [comment]
こちらでは「極端に」とは体感できなかったのですが、軽減策を試しました。
こちらでよろしければクローズします。
[お試しページ](https://nanasunana.github.io/)

**Comment by Mazzn1987** [comment]
早速のご対応ありがとうございます。
此方でも症状が大幅に軽減しました。
ありがとうございます。
