### ISSUE TITLE
[suggestion] the shadow related the height

### ISSUE THREAD

**Issue by zeteticl** [NanasuNANA/UdonariumWithFly#8]
something strange when shadow still origin place if the height is change

![image](https://user-images.githubusercontent.com/23254376/118225453-c01be300-b4b7-11eb-9ea7-f7df31fd300f.png)

**Comment by NanasuNANA** [comment]
The source of the remodeling of Udonarium also has the shadow of the terrain, but there is no concept of a light source. We considered making it smaller according to changes in altitude, but prioritized visibility.
